name: Deploy to Firebase Hosting
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup mint-lang
        uses: fabasoad/setup-mint-action@v1.0.7
        with:
          version: 0.10.0
      - name: Run tests
        run: mint test
      - name: Make build
        run: mint build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PSY_ADMIN }}'
          projectId: psy-admin
          channelId: live

